USE [master]
GO

CREATE DATABASE [CarDbDev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarDbDev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CarDbDev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarDbDev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CarDbDev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarDbDev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarDbDev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarDbDev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarDbDev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarDbDev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarDbDev] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarDbDev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarDbDev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarDbDev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarDbDev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarDbDev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarDbDev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarDbDev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarDbDev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarDbDev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarDbDev] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CarDbDev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarDbDev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarDbDev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarDbDev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarDbDev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarDbDev] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CarDbDev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarDbDev] SET RECOVERY FULL 
GO

ALTER DATABASE [CarDbDev] SET  MULTI_USER 
GO

ALTER DATABASE [CarDbDev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarDbDev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarDbDev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarDbDev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CarDbDev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CarDbDev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CarDbDev] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CarDbDev] SET  READ_WRITE 
GO

